spring.application.name=demo-gc

spring.datasource.url=jdbc:postgresql://localhost:5432/demo_gc_db
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Seguridad JWT
jwt.token.validity=18000
jwt.signing.key=mi_clave_super_segura_1234567890123456jwt.authorities.key=roles
jwt.authorities.key=roles
jwt.token.prefix=Bearer
jwt.header.string=Authorization
